import { onValue } from 'firebase/database'
import { useState, useEffect } from 'react'
import Message from '../Message/Message.tsx'
import Input from '../Input/Input.tsx'
import './chatStyles.css'

/*

This component handles reading the messages and rendering the Message & Input components.

*/

interface chatProps {
	databaseRef: any // firebase database ref
	sendMessage:(message:string) => void // sendMessage function from main.tsx
}

export default function Chat({databaseRef, sendMessage}:chatProps) {
	const [messages, setMessages] = useState<Array<{message:string, createdAt:number}>>([])
	
	// This only runs on mount
	useEffect(() =>
		// onValue runs the callback whenever there is a change in the database AND on first call,
		// if the database is empty snapshot.val() returns null
		onValue(databaseRef, snapshot => setMessages(snapshot.val() ?? []))
	, [])

	const messageComponents = Object.entries(messages) // We get all the message entries
	.sort((a, b) => b[1].createdAt - a[1].createdAt) // Sort them from newest at the top
	.map(curMessage => <Message message={curMessage[1].message} key={curMessage[0]} />) // And lastly create the message components
	// note: curMessage[0] is the key of the message which is randomly generated by firebase

	return(
		<div className="wrapper">
			<div className="chatWrapper">
				{messageComponents}
			</div>
			<Input sendMessage={sendMessage} />
		</div>
	)
}